name: Igneous Smart Server
group_id: com.cerner.igneous
artifact_id: igneous-smart_server
version: 1.32.0
test: rake
doc: tomdoc
package:
  type: rails
  files:
    - engines/**/*
jira:
  url: https://jira2.cerner.com
  project: OPENSVC
  component: 25820
coverage:
  directory: coverage
github:
  project_url: https://github.cerner.com/Igneous/igneous-smart_server/
repository:
  id: cerner-main-release
  url: http://repo.release.cerner.corp/main/repo/
site_repository:
  id: cerner-main-release-site
  url: http://repo.release.cerner.corp/main/site/
snapshot_repository:
  id: exodus-snapshot
  url: http://repo.exodus.cerner.corp/snapshot-repo/
snapshot_site_repository:
  id: exodus-snapshot-site
  url: http://repo.exodus.cerner.corp/snapshot-site/
philter:
  ruby:
    exclusions: ['target/**/*',
                 'tmp/**/*',
                 'config/initializers/secret_token.rb',
                 'db/**/*']
  javascript:
    exclusions: ['target/**/*',
                 'tmp/**/*',
                 'engines/**/vendor/**/*',
                 'coverage/assets/**/*',
                 'public/assets/*',
                 'public/**/lib/fhir-client.js',
                 'public/cardiac-risk-app/**/*',
                 'public/growth-chart-app/**/*',
                 'public/cardiac-risk-app-2.0/**/*',
                 'public/growth-chart-app-2.0/**/*',
                 'public/fhir-client/*',
                 'public/fhir-client-dstu2/fhir-client.js',
                 'public/fhir-client-dstu2/fhir-client.min.js',
                 'public/embedded_content/*',
                 'public/polyfill/*']
    globals: ['XMLCclRequest', 'Canadarm', 'FHIR']
