---
development:
  user_roster:
    base_url: https://user-roster.api.devcernercentral.com
production:
  user_roster:
    base_url: https://user-roster.api.devcernercentral.com
test:
  user_roster:
    base_url: http://user-roster.example.com
